src/components/Header.js, src/components/Layout.js, src/pages/jobs.js
- Header 컴포넌트 생성
- 모든 Layout에 Header 적용
=> Feat: Header 생성

src/pages/jobs.js
공고 "지원하기" 버튼 누르면 /detail 페이지로 넘어가게 수정
=> Fix: /jobs 페이지랑 /detail 페이지 연결

src/components/Header.js, src/pages/login.js, src/pages/signup.js, src/styles/globals.css
- 헤더 상단 -> 좌측으로 이동 (CSS 수정)
- Login & Signup 페이지도 동일 레이아웃 지정
=> Design: 헤더 & 레이아웃 변경

src/components/Header.js, src/components/Layout.js, src/pages/index.js, src/pages/jobs.js, src/styles/globals.css, tailwind.config.js
- CSS를 적용하여 Layout과 메인 색상들을 변경하였습니다.
- 헤더 부분의 경우 페이지 이동 시 색상이 유지될 수 있도록
- 코드를 추가하였습니다.
=> Design: 전체 페이지+헤더 레이아웃 변경

src/firebase/index.js, src/pages/api/api.js, src/pages/api/auth/signup.js, src/pages/detail.js
유저 모델 변경
일반 로그인 (credentials) 유저도 세션 속에 아이디값을 반환
API 함수 추가
pdf 업로드 / 삭제 / 사용자가 가진 모든 pdf 파일 불러오기 api 정의
detail.js에서 불러오게 만듦
문서 오류 수정
detail.js에서 html 태그 내부에 class로 선언된 부분을 className으로 변경
=> detail 페이지 관련 기능 추가

src/components/Calendar.js, src/components/CalendarBody.js, src/components/Date.js
- CalendarBody의 일부가 커밋되지 않은 채로 pull request를 보냈어서 다시 커밋 했습니다.
- 다른달 날짜칸의 요소들은 이번달 날짜 칸의 요소의 텍스트 및 배경 색상에 투명도 50%를 주었는데,
변수로 할당한 색상들이 제대로 반영되지 않았습니다. 다시 하드코딩으로 색상을 부여해 오류를 잡았습니다.
=> Css 미적용 오류 수정 및 미반영 commit 재업로드

src/components/Header.js, src/data/index.js, src/pages/review/[id].js, src/pages/review/index.js
- 헤더에 회고 페이지로 가는 링크 추가 (/review)
- 더미데이터 수정 (회고 Q&A 배열 포함하게끔)
```
reviews: [
{
question: "question",
answer: "answer",
}, ...
]
```
- 회고 Q&A 불러와서 띄워주고, 토글하는 기능
- 회고 Q&A 추가 기능
- 회고 Q&A 수정 기능
=> Feat: 회고 페이지 추가

src/components/Header.js, src/pages/detail.js, src/pages/mypage.js
- 마이페이지 기본 레이아웃 구현
- 헤더에서 마이페이지 연결되는 링크 생성
=> Init: 마이페이지 틀 생성

src/data/index.js, src/pages/review/[id].js, src/styles/globals.css
=> Feat: 회고 태그 & 총평 구현

next.config.js, src/components/Header.js, src/pages/api/api.js, src/pages/api/auth/[...nextauth].js, src/pages/api/auth/signup.js, src/pages/review/[id].js
-로그인시 프로필 사진 정보도 반영
-sns로그인시 새로운 firestore 문서 제목으로 session id 설정 (getDoc 사용을 위함)
-태그 post api
-태그 get api
=> 로그인 로직 수정 / 태그 관련 api

src/components/Header.js
- 헤더에서 누락된 이미지 import문을 추가했습니다.
=> Fix: Import 문 추가

src/components/Header.js
컨플릭 해결 과정에서 해당 기능이 사라져서 다시 추가했습니다
=> feat: sns 로그인시 프로필 사진 정보 받아오기

src/api/apply.js, src/api/cv.js, src/api/file.js, src/api/job.js, src/api/review.js, src/api/tag.js
- api/apply.js
- api/cv.js
- api/file.js
- api/job.js
- api/review.js
- api/tag.js
=> Feat: API 구조 짜기

src/api/cv.js, src/api/review.js, src/pages/review/[id].js
=> Feat: reviewAPI & cvAPI

src/api/job.js, src/pages/review/[id].js, src/pages/review/index.js
- job Id 로 job 불러오는 API 구현
- reviews 페이지랑 연결
=> Feat: getJob API

src/api/tag.js
review별 태그 불러오는 api에서 변수명이 잘못 설정되어 있었습니다
=> fix: 변수명 변경

src/api/cv.js, src/api/review.js, src/api/tag.js, src/pages/review/[id].js
- review 생성할 때 tag에 review id 배열에 추가
- review 받아올 때, 프론트 단에서 가공해서 tag도 객체에 추가
=> Feat: Tag랑 Review 연결

src/api/file.js, src/pages/mypage.js
-pdf 업로드
-유저별 pdf 가져오기
-job별 pdf 가져오기
-마이페이지 pdf 업로드 버튼
=> feat: pdf 관련 api 일부 구현

src/pages/detail.js, src/pages/mypage.js
-유저가 올린 파일 확인 가능 (embed)
-파일 추가로 업로드 가능, api연동
=> feat: 마이페이지 구성 / api 연결

src/api/file.js, src/pages/mypage.js
pdf 삭제 버튼을 만들었습니다.
deleteFile api를 완성했습니다.
=> 마이페이지 기능 추가

src/api/file.js, src/pages/detail/[id].js
-updateFile api 완성
-detail 페이지와 모든 api (유저, job별 파일 불러오기, 파일 등록하기) 연결
-db 기반으로 파일 임베드하도록 수정
=> 디테일 페이지 파일 api 연결

src/components/SnsSignInForm.js, src/pages/api/auth/[...nextauth].js
네이버 로그인시 name이 undefined로 받아와짐 + 네이버 승인 문제로 네이버 로그인 기능이 삭제되었습니다.
=> fix: 네이버 로그인 삭제

src/api/file.js, src/pages/mypage.js
pdf 이외의 확장자 파일을 업로드하려고 시도할 경우 alert가 뜨고 업로드가 실행되지 않게 만들었습니다.
=> fix: pdf 외의 확장자 업로드 예외처리

src/api/file.js, src/pages/mypage.js
=> pdf api 보완

src/components/Calendar.js, src/components/Header.js
-헤더에서 review, document 안 보이게 설정
-일정 추가 시도시 alert 후 로그인 페이지로 리다이렉트
=> 로그인 안 된 유저 처리 기능 추가
